-- ============================================================
-- TexitArchenemy - PostgreSQL Schema
-- Converted from T-SQL / MSSQL
-- ============================================================

-- Run as superuser or a role with CREATEDB, then switch to the new DB.
-- Example:
--   createdb texit_archenemy
--   psql -d texit_archenemy -f DatabaseCreation_PostgreSQL.sql


-- ============================================================
-- EXTENSIONS
-- ============================================================

-- Used for fuzzy skill-name search (search_uma_skill / uma_skills_trgm index).
CREATE EXTENSION IF NOT EXISTS pg_trgm;


-- ============================================================
-- TABLES
-- ============================================================

CREATE TABLE discord_auth (
    token VARCHAR(60) NOT NULL
);

CREATE TABLE twitter_auth (
    api_key    VARCHAR(25)  NOT NULL,
    api_secret VARCHAR(50)  NOT NULL,
    api_token  VARCHAR(116) NOT NULL
);

-- GENERATED BY DEFAULT (not ALWAYS) lets us INSERT explicit IDs during data migration.
-- After migrating data, reset the sequence (see migration guide).
CREATE TABLE channel_types (
    channel_type_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_type_description VARCHAR(10) NOT NULL
);
INSERT INTO channel_types (channel_type_description) VALUES ('text'), ('voice');

-- BIT -> BOOLEAN, DEFAULT 0 -> DEFAULT FALSE
CREATE TABLE discord_channels (
    channel_id      VARCHAR(20) PRIMARY KEY,
    guild_id        VARCHAR(20) NOT NULL,
    channel_type_id INT         NOT NULL DEFAULT 1,
    repost_check    BOOLEAN     NOT NULL DEFAULT FALSE,
    pixiv_expand    BOOLEAN     NOT NULL DEFAULT FALSE,
    FOREIGN KEY (channel_type_id) REFERENCES channel_types(channel_type_id)
);

CREATE TABLE twitter_rules (
    tag        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_value VARCHAR(512) UNIQUE NOT NULL
);

CREATE TABLE rule_channel_relation (
    tag        INT         NOT NULL,
    channel_id VARCHAR(20) NOT NULL,
    PRIMARY KEY (tag, channel_id),
    FOREIGN KEY (tag)        REFERENCES twitter_rules(tag)       ON DELETE CASCADE,
    FOREIGN KEY (channel_id) REFERENCES discord_channels(channel_id) ON DELETE CASCADE
);

CREATE TABLE link_types (
    link_type_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    link_type_description VARCHAR(10) NOT NULL UNIQUE
);
INSERT INTO link_types (link_type_description) VALUES ('Twitter'), ('Pixiv'), ('Artstation');

CREATE TABLE repost_repository (
    message_id   VARCHAR(20) NOT NULL,
    channel_id   VARCHAR(20) NOT NULL,
    link_id      VARCHAR(20) NOT NULL,
    link_type_id INT         NOT NULL,
    PRIMARY KEY (message_id, channel_id, link_id, link_type_id),
    FOREIGN KEY (link_type_id) REFERENCES link_types(link_type_id),
    FOREIGN KEY (channel_id)   REFERENCES discord_channels(channel_id) ON DELETE CASCADE
);

CREATE TABLE draw_a_box_warmups (
    warmup VARCHAR(50) NOT NULL,
    lesson INT         NOT NULL
);
INSERT INTO draw_a_box_warmups (warmup, lesson) VALUES
    ('Superimposed Lines',              1),
    ('Table of Ellipses',               1),
    ('Ellipses in Planes',              1),
    ('Funnels',                         1),
    ('Plotted Perspective',             1),
    ('Rough Perspective',               1),
    ('Rotated Boxes',                   1),
    ('Organic Perspective',             1),
    ('Organic Arrows',                  2),
    ('Organic Forms with Contour Lines',2),
    ('Texture Analysis',                2),
    ('Dissections',                     2),
    ('Form Intersections',              2),
    ('Organic Intersections',           2);

CREATE TABLE draw_a_box_box_challenge (
    user_id     VARCHAR(20) PRIMARY KEY,
    boxes_drawn INT NOT NULL
);

-- ---- Uma Musume ----

CREATE TABLE uma_characters (
    char_id           INT PRIMARY KEY,
    name_en           VARCHAR(200) NOT NULL,
    name_jp           VARCHAR(200),
    name_tw           VARCHAR(200),
    url_name          VARCHAR(200),
    height            INT,
    birth_day         INT,
    birth_month       INT,
    birth_year        INT,
    sex               INT,
    bust              INT,
    waist             INT,
    hip               INT,
    va_en             VARCHAR(200),
    va_ja             VARCHAR(200),
    va_link           VARCHAR(500),
    playable          BOOLEAN,
    playable_en       BOOLEAN,
    active_en         BOOLEAN     NOT NULL DEFAULT FALSE,
    rl_active         VARCHAR(50),
    rl_country        VARCHAR(10),
    rl_death          VARCHAR(20),
    rl_earnings       BIGINT,
    rl_earnings_other JSONB,
    rl_races          INT,
    rl_record         VARCHAR(20),
    rl_wins           INT,
    last_updated      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE uma_cards (
    card_id     INT PRIMARY KEY,
    char_id     INT          NOT NULL,
    name_en     VARCHAR(200) NOT NULL,
    version     VARCHAR(100),
    title_en_gl VARCHAR(200)
);

CREATE TABLE uma_skills (
    skill_id              INT PRIMARY KEY,
    parent_skill_id       INT,
    name_en               VARCHAR(200) NOT NULL,
    name_jp               VARCHAR(200),
    rarity                INT          NOT NULL,
    icon_id               INT,
    available_in_en       BOOLEAN      NOT NULL DEFAULT FALSE,
    condition_groups_json JSONB        NOT NULL,
    conditions_hash       VARCHAR(64),
    last_llm_update       TIMESTAMPTZ,
    last_updated          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    base_time_ms          INT,
    FOREIGN KEY (parent_skill_id) REFERENCES uma_skills(skill_id)
);

-- Powers fuzzy skill-name lookups in search_uma_skill().
CREATE INDEX uma_skills_trgm ON uma_skills USING gin (name_en gin_trgm_ops);

-- Note: char_id has no FK to uma_cards on the deployed DB — captured as-is.
CREATE TABLE uma_skill_characters (
    skill_id INT NOT NULL,
    char_id  INT NOT NULL,
    PRIMARY KEY (skill_id, char_id),
    FOREIGN KEY (skill_id) REFERENCES uma_skills(skill_id) ON DELETE CASCADE
);

CREATE TABLE uma_skill_readable_groups (
    skill_id              INT NOT NULL,
    group_index           INT NOT NULL,
    readable_precondition TEXT,
    readable_condition    TEXT,
    readable_effects      TEXT,
    PRIMARY KEY (skill_id, group_index),
    FOREIGN KEY (skill_id) REFERENCES uma_skills(skill_id) ON DELETE CASCADE
);

CREATE TABLE uma_condition_types (
    condition_name   VARCHAR(100) PRIMARY KEY,
    description      TEXT         NOT NULL,
    example          VARCHAR(200),
    example_meaning  TEXT
);

CREATE TABLE uma_effect_types (
    effect_type_id   INT PRIMARY KEY,
    key_name         VARCHAR(100) NOT NULL,
    display_name     VARCHAR(100) NOT NULL,
    neg_display_name VARCHAR(100)
);

CREATE TABLE uma_manifest_hashes (
    manifest_key VARCHAR(100) PRIMARY KEY,
    hash_token   VARCHAR(20) NOT NULL,
    last_checked TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_changed TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================
-- FUNCTIONS  (replacing T-SQL stored procedures)
--
-- All data-returning procedures become FUNCTIONS (RETURNS TABLE).
-- They are called from C# as: SELECT * FROM func_name(@p1, @p2)
-- ============================================================

-- ---- Credentials ----

CREATE OR REPLACE FUNCTION get_discord_creds()
RETURNS TABLE(token VARCHAR(60))
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT d.token FROM discord_auth d LIMIT 1;
END;
$$;

CREATE OR REPLACE FUNCTION get_twitter_creds()
RETURNS TABLE(api_key VARCHAR(25), api_secret VARCHAR(50), api_token VARCHAR(116))
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT t.api_key, t.api_secret, t.api_token FROM twitter_auth t LIMIT 1;
END;
$$;

-- ---- Repost checking ----

-- Returns (channel_id, message_id) of existing repost, or ('-1', '-1') if not a repost (and inserts it).
CREATE OR REPLACE FUNCTION check_repost(
    p_channel_id          VARCHAR(20),
    p_message_id          VARCHAR(20),
    p_link_id             VARCHAR(20),
    p_link_type_description VARCHAR(20)
)
RETURNS TABLE(channel_id VARCHAR(20), message_id VARCHAR(20))
LANGUAGE plpgsql AS $$
DECLARE
    v_count INT;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM repost_repository r
    INNER JOIN link_types lt ON r.link_type_id = lt.link_type_id
    WHERE r.channel_id              = p_channel_id
      AND r.link_id                 = p_link_id
      AND lt.link_type_description  = p_link_type_description;

    IF v_count > 0 THEN
        RETURN QUERY
            SELECT r.channel_id, r.message_id
            FROM repost_repository r
            INNER JOIN link_types lt ON r.link_type_id = lt.link_type_id
            WHERE r.channel_id              = p_channel_id
              AND r.link_id                 = p_link_id
              AND lt.link_type_description  = p_link_type_description;
    ELSE
        INSERT INTO repost_repository (channel_id, message_id, link_id, link_type_id)
        VALUES (
            p_channel_id,
            p_message_id,
            p_link_id,
            (SELECT lt.link_type_id FROM link_types lt WHERE lt.link_type_description = p_link_type_description)
        );
        RETURN QUERY SELECT '-1'::VARCHAR(20), '-1'::VARCHAR(20);
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION preemptive_repost_check(
    p_channel_id            VARCHAR(20),
    p_link_id               VARCHAR(20),
    p_link_type_description VARCHAR(20)
)
RETURNS TABLE(repost_number BIGINT)
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY
        SELECT COUNT(*)
        FROM repost_repository r
        INNER JOIN link_types lt ON r.link_type_id = lt.link_type_id
        WHERE r.channel_id              = p_channel_id
          AND r.link_id                 = p_link_id
          AND lt.link_type_description  = p_link_type_description;
END;
$$;

CREATE OR REPLACE FUNCTION is_repost_channel(p_channel_id VARCHAR(20))
RETURNS TABLE(repost_check BOOLEAN)
LANGUAGE plpgsql AS $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM discord_channels dc WHERE dc.channel_id = p_channel_id) THEN
        RETURN QUERY SELECT FALSE;
    ELSE
        RETURN QUERY
            SELECT dc.repost_check
            FROM discord_channels dc
            WHERE dc.channel_id = p_channel_id;
    END IF;
END;
$$;

-- ---- Twitter rules ----

CREATE OR REPLACE FUNCTION get_twitter_rules()
RETURNS TABLE(tag INT, rule_value VARCHAR(512))
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT tr.tag, tr.rule_value FROM twitter_rules tr;
END;
$$;

CREATE OR REPLACE FUNCTION get_twitter_rule_channels(p_tag INT)
RETURNS TABLE(channel_id VARCHAR(20))
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY
        SELECT rcr.channel_id
        FROM rule_channel_relation rcr
        WHERE rcr.tag = p_tag;
END;
$$;

-- Returns (tag, added): tag=-1 and added=false means the channel<->rule pair already existed.
CREATE OR REPLACE FUNCTION add_twitter_rule(
    p_channel_id VARCHAR(20),
    p_guild_id   VARCHAR(20),
    p_rule_value VARCHAR(512)
)
RETURNS TABLE(tag INT, added BOOLEAN)
LANGUAGE plpgsql AS $$
DECLARE
    v_tag           INT;
    v_actually_added BOOLEAN := FALSE;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM discord_channels dc WHERE dc.channel_id = p_channel_id) THEN
        INSERT INTO discord_channels (channel_id, guild_id) VALUES (p_channel_id, p_guild_id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM twitter_rules tr WHERE tr.rule_value = p_rule_value) THEN
        INSERT INTO twitter_rules (rule_value) VALUES (p_rule_value);
        v_actually_added := TRUE;
    END IF;

    SELECT tr.tag INTO v_tag FROM twitter_rules tr WHERE tr.rule_value = p_rule_value;

    BEGIN
        INSERT INTO rule_channel_relation (tag, channel_id) VALUES (v_tag, p_channel_id);
        RETURN QUERY SELECT v_tag, v_actually_added;
    EXCEPTION WHEN unique_violation OR foreign_key_violation THEN
        RETURN QUERY SELECT -1::INT, FALSE::BOOLEAN;
    END;
END;
$$;

-- ---- Draw-a-Box ----

CREATE OR REPLACE FUNCTION get_box_warmup(p_lesson INT)
RETURNS TABLE(warmup VARCHAR(50))
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY
        SELECT w.warmup
        FROM draw_a_box_warmups w
        WHERE w.lesson <= p_lesson;
END;
$$;

-- T-SQL used a VALUES table trick for GREATEST(x, 0). PostgreSQL has GREATEST() natively.
CREATE OR REPLACE FUNCTION update_box_challenge_progress(
    p_user_id    VARCHAR(20),
    p_boxes_drawn INT
)
RETURNS TABLE(boxes_drawn INT)
LANGUAGE plpgsql AS $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM draw_a_box_box_challenge dbc WHERE dbc.user_id = p_user_id) THEN
        INSERT INTO draw_a_box_box_challenge (user_id, boxes_drawn)
        VALUES (p_user_id, GREATEST(p_boxes_drawn, 0));
    ELSE
        UPDATE draw_a_box_box_challenge dbc
        SET boxes_drawn = GREATEST(dbc.boxes_drawn + p_boxes_drawn, 0)
        WHERE dbc.user_id = p_user_id;
    END IF;

    RETURN QUERY
        SELECT dbc.boxes_drawn
        FROM draw_a_box_box_challenge dbc
        WHERE dbc.user_id = p_user_id;
END;
$$;

CREATE OR REPLACE FUNCTION get_box_challenge_progress(p_user_id VARCHAR(20))
RETURNS TABLE(boxes_drawn INT)
LANGUAGE plpgsql AS $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM draw_a_box_box_challenge dbc WHERE dbc.user_id = p_user_id) THEN
        RETURN QUERY SELECT 0::INT;
    ELSE
        RETURN QUERY
            SELECT dbc.boxes_drawn
            FROM draw_a_box_box_challenge dbc
            WHERE dbc.user_id = p_user_id;
    END IF;
END;
$$;


-- ---- Uma Musume ----

CREATE OR REPLACE FUNCTION get_condition_descriptions(p_names VARCHAR(100)[])
RETURNS TABLE(condition_name VARCHAR(100), description TEXT, example VARCHAR(200), example_meaning TEXT)
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY
        SELECT ct.condition_name, ct.description, ct.example, ct.example_meaning
        FROM uma_condition_types ct
        WHERE ct.condition_name = ANY(p_names);
END;
$$;

CREATE OR REPLACE FUNCTION get_manifest_hash(p_key VARCHAR(100))
RETURNS TABLE(hash_token VARCHAR(20))
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY
        SELECT mh.hash_token
        FROM uma_manifest_hashes mh
        WHERE mh.manifest_key = p_key;
END;
$$;

CREATE OR REPLACE FUNCTION get_uma_conditions_hash(p_skill_id INT)
RETURNS TABLE(conditions_hash VARCHAR(64))
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY
        SELECT s.conditions_hash
        FROM uma_skills s
        WHERE s.skill_id = p_skill_id;
END;
$$;

CREATE OR REPLACE FUNCTION get_uma_effect_type_names(p_type_ids INT[])
RETURNS TABLE(effect_type_id INT, display_name VARCHAR(100))
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY
        SELECT et.effect_type_id, et.display_name
        FROM uma_effect_types et
        WHERE et.effect_type_id = ANY(p_type_ids);
END;
$$;

CREATE OR REPLACE FUNCTION get_uma_skill_full(p_skill_id INT)
RETURNS TABLE(
    skill_id         INT,
    name_en          VARCHAR(200),
    rarity           INT,
    available_in_en  BOOLEAN,
    base_time_ms     INT,
    last_llm_update  TIMESTAMPTZ,
    gene_skill_id    INT,
    gene_name_en     VARCHAR(200),
    gene_base_time_ms INT,
    character_names  TEXT
)
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY
        SELECT
            s.skill_id,
            s.name_en,
            s.rarity,
            s.available_in_en,
            s.base_time_ms,
            s.last_llm_update,
            g.skill_id,
            g.name_en,
            g.base_time_ms,
            (
                SELECT string_agg(
                    c.name_en || ' [' ||
                    COALESCE(initcap(replace(c.version, '_', ' ')), 'Original') || ']',
                    ', ' ORDER BY c.name_en, c.version NULLS FIRST
                )
                FROM uma_skill_characters sc
                JOIN uma_cards c ON c.card_id = sc.char_id
                WHERE sc.skill_id = s.skill_id
            )
        FROM uma_skills s
        LEFT JOIN uma_skills g ON g.parent_skill_id = s.skill_id
        WHERE s.skill_id = p_skill_id;
END;
$$;

CREATE OR REPLACE FUNCTION get_uma_skill_groups(p_skill_id INT)
RETURNS TABLE(group_index INT, readable_precondition TEXT, readable_condition TEXT, readable_effects TEXT)
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY
        SELECT g.group_index, g.readable_precondition, g.readable_condition, g.readable_effects
        FROM uma_skill_readable_groups g
        WHERE g.skill_id = p_skill_id
        ORDER BY g.group_index;
END;
$$;

CREATE OR REPLACE FUNCTION get_uma_skill_parent_id(p_skill_id INT)
RETURNS TABLE(parent_skill_id INT)
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY
        SELECT s.parent_skill_id
        FROM uma_skills s
        WHERE s.skill_id = p_skill_id;
END;
$$;

CREATE OR REPLACE FUNCTION get_uma_skills_missing_descriptions()
RETURNS TABLE(skill_id INT, condition_groups_json JSONB)
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY
        SELECT s.skill_id, s.condition_groups_json
        FROM uma_skills s
        WHERE s.conditions_hash IS DISTINCT FROM
              encode(sha256(s.condition_groups_json::text::bytea), 'hex')
        ORDER BY
            s.available_in_en DESC,      -- EN skills first
            s.parent_skill_id NULLS FIRST, -- parents before gene versions
            s.skill_id;
END;
$$;

CREATE OR REPLACE FUNCTION search_uma_skill(p_query TEXT, p_limit INT, p_threshold REAL)
RETURNS TABLE(skill_id INT, parent_skill_id INT, name_en VARCHAR(200), rarity INT, available_in_en BOOLEAN, match_similarity REAL)
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY
        SELECT
            s.skill_id,
            s.parent_skill_id,
            s.name_en,
            s.rarity,
            s.available_in_en,
            similarity(s.name_en, p_query) AS sim
        FROM uma_skills s
        WHERE s.parent_skill_id IS NULL
          AND similarity(s.name_en, p_query) >= p_threshold
        ORDER BY sim DESC
        LIMIT p_limit;
END;
$$;


-- ============================================================
-- PROCEDURES  (void operations — no result set returned)
-- Called from C# as: CALL proc_name(@p1, @p2)
-- ============================================================

CREATE OR REPLACE PROCEDURE mark_as_repost_channel(
    p_channel_id VARCHAR(20),
    p_guild_id   VARCHAR(20)
)
LANGUAGE plpgsql AS $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM discord_channels dc WHERE dc.channel_id = p_channel_id) THEN
        INSERT INTO discord_channels (channel_id, channel_type_id, guild_id, pixiv_expand, repost_check)
        VALUES (p_channel_id, 1, p_guild_id, FALSE, TRUE);
    ELSE
        UPDATE discord_channels
        SET repost_check = TRUE
        WHERE channel_id = p_channel_id;
    END IF;
END;
$$;

CREATE OR REPLACE PROCEDURE delete_twitter_rule(p_tag INT, p_channel_id VARCHAR(20))
LANGUAGE plpgsql AS $$
BEGIN
    DELETE FROM rule_channel_relation
    WHERE tag = p_tag AND channel_id = p_channel_id;
END;
$$;

-- Internal helper called by trigger functions below
CREATE OR REPLACE PROCEDURE remove_useless_channels()
LANGUAGE plpgsql AS $$
BEGIN
    DELETE FROM discord_channels
    WHERE pixiv_expand  = FALSE
      AND repost_check  = FALSE
      AND channel_id NOT IN (SELECT rcr.channel_id FROM rule_channel_relation rcr);
END;
$$;


-- ---- Uma Musume ----

CREATE OR REPLACE PROCEDURE delete_uma_skill_readable_groups(p_skill_id INT)
LANGUAGE plpgsql AS $$
BEGIN
    DELETE FROM uma_skill_readable_groups WHERE skill_id = p_skill_id;
END;
$$;

CREATE OR REPLACE PROCEDURE insert_uma_condition_type(
    p_name             VARCHAR(100),
    p_description      TEXT,
    p_example          VARCHAR(200),
    p_example_meaning  TEXT
)
LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO uma_condition_types (condition_name, description, example, example_meaning)
    VALUES (p_name, p_description, p_example, p_example_meaning)
    ON CONFLICT DO NOTHING;
END;
$$;

CREATE OR REPLACE PROCEDURE truncate_uma_condition_types()
LANGUAGE plpgsql AS $$
BEGIN
    TRUNCATE uma_condition_types;
END;
$$;

CREATE OR REPLACE PROCEDURE update_skill_conditions_hash(p_skill_id INT)
LANGUAGE plpgsql AS $$
BEGIN
    UPDATE uma_skills
    SET conditions_hash = encode(sha256(condition_groups_json::text::bytea), 'hex'),
        last_llm_update = now()
    WHERE skill_id = p_skill_id;
END;
$$;

CREATE OR REPLACE PROCEDURE update_skill_readable_text(
    p_skill_id             INT,
    p_readable_conditions  TEXT,
    p_readable_effects     TEXT
)
LANGUAGE plpgsql AS $$
BEGIN
    UPDATE uma_skills
    SET readable_conditions = p_readable_conditions,
        readable_effects    = p_readable_effects,
        last_llm_update     = NOW()
    WHERE skill_id = p_skill_id;
END;
$$;

CREATE OR REPLACE PROCEDURE upsert_manifest_hash(p_key VARCHAR(100), p_hash VARCHAR(20))
LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO uma_manifest_hashes (manifest_key, hash_token, last_checked, last_changed)
    VALUES (p_key, p_hash, NOW(), NOW())
    ON CONFLICT (manifest_key) DO UPDATE
        SET last_checked = NOW(),
            hash_token   = p_hash,
            last_changed = CASE
                               WHEN uma_manifest_hashes.hash_token <> EXCLUDED.hash_token
                               THEN NOW()
                               ELSE uma_manifest_hashes.last_changed
                           END;
END;
$$;

CREATE OR REPLACE PROCEDURE upsert_uma_card(
    p_card_id     INT,
    p_char_id     INT,
    p_name_en     VARCHAR(200),
    p_version     VARCHAR(100),
    p_title_en_gl VARCHAR(200)
)
LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO uma_cards (card_id, char_id, name_en, version, title_en_gl)
    VALUES (p_card_id, p_char_id, p_name_en, p_version, p_title_en_gl)
    ON CONFLICT (card_id) DO UPDATE SET
        char_id     = EXCLUDED.char_id,
        name_en     = EXCLUDED.name_en,
        version     = EXCLUDED.version,
        title_en_gl = EXCLUDED.title_en_gl;
END;
$$;

CREATE OR REPLACE PROCEDURE upsert_uma_character(
    p_char_id            INT,
    p_name_en            VARCHAR(200),
    p_name_jp            VARCHAR(200),
    p_name_tw            VARCHAR(200),
    p_url_name           VARCHAR(200),
    p_height             INT,
    p_birth_day          INT,
    p_birth_month        INT,
    p_birth_year         INT,
    p_sex                INT,
    p_bust               INT,
    p_waist              INT,
    p_hip                INT,
    p_va_en              VARCHAR(200),
    p_va_ja              VARCHAR(200),
    p_va_link            VARCHAR(500),
    p_playable           BOOLEAN,
    p_playable_en        BOOLEAN,
    p_active_en          BOOLEAN,
    p_rl_active          VARCHAR(50),
    p_rl_country         VARCHAR(10),
    p_rl_death           VARCHAR(20),
    p_rl_earnings        BIGINT,
    p_rl_earnings_other  JSONB,
    p_rl_races           INT,
    p_rl_record          VARCHAR(20),
    p_rl_wins            INT
)
LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO uma_characters (
        char_id, name_en, name_jp, name_tw, url_name,
        height, birth_day, birth_month, birth_year, sex,
        bust, waist, hip,
        va_en, va_ja, va_link,
        playable, playable_en, active_en,
        rl_active, rl_country, rl_death, rl_earnings, rl_earnings_other,
        rl_races, rl_record, rl_wins,
        last_updated
    )
    VALUES (
        p_char_id, p_name_en, p_name_jp, p_name_tw, p_url_name,
        p_height, p_birth_day, p_birth_month, p_birth_year, p_sex,
        p_bust, p_waist, p_hip,
        p_va_en, p_va_ja, p_va_link,
        p_playable, p_playable_en, p_active_en,
        p_rl_active, p_rl_country, p_rl_death, p_rl_earnings, p_rl_earnings_other,
        p_rl_races, p_rl_record, p_rl_wins,
        NOW()
    )
    ON CONFLICT (char_id) DO UPDATE
        SET name_en             = EXCLUDED.name_en,
            name_jp             = EXCLUDED.name_jp,
            name_tw             = EXCLUDED.name_tw,
            url_name            = EXCLUDED.url_name,
            height              = EXCLUDED.height,
            birth_day           = EXCLUDED.birth_day,
            birth_month         = EXCLUDED.birth_month,
            birth_year          = EXCLUDED.birth_year,
            sex                 = EXCLUDED.sex,
            bust                = EXCLUDED.bust,
            waist               = EXCLUDED.waist,
            hip                 = EXCLUDED.hip,
            va_en               = EXCLUDED.va_en,
            va_ja               = EXCLUDED.va_ja,
            va_link             = EXCLUDED.va_link,
            playable            = EXCLUDED.playable,
            playable_en         = EXCLUDED.playable_en,
            active_en           = EXCLUDED.active_en,
            rl_active           = EXCLUDED.rl_active,
            rl_country          = EXCLUDED.rl_country,
            rl_death            = EXCLUDED.rl_death,
            rl_earnings         = EXCLUDED.rl_earnings,
            rl_earnings_other   = EXCLUDED.rl_earnings_other,
            rl_races            = EXCLUDED.rl_races,
            rl_record           = EXCLUDED.rl_record,
            rl_wins             = EXCLUDED.rl_wins,
            last_updated        = NOW();
END;
$$;

-- Three overloads of upsert_uma_skill are deployed on prod; captured here
-- as-is rather than consolidated.
CREATE OR REPLACE PROCEDURE upsert_uma_skill(
    p_skill_id              INT,
    p_parent_skill_id       INT,
    p_name_en               VARCHAR(200),
    p_name_jp               VARCHAR(200),
    p_rarity                INT,
    p_icon_id               INT,
    p_available_in_en       BOOLEAN,
    p_condition_groups_json JSONB,
    p_base_time_ms          INT
)
LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO uma_skills (
        skill_id, parent_skill_id, name_en, name_jp, rarity, icon_id,
        available_in_en, condition_groups_json, base_time_ms
    )
    VALUES (
        p_skill_id, p_parent_skill_id, p_name_en, p_name_jp, p_rarity, p_icon_id,
        p_available_in_en, p_condition_groups_json, p_base_time_ms
    )
    ON CONFLICT (skill_id) DO UPDATE SET
        parent_skill_id       = EXCLUDED.parent_skill_id,
        name_en               = EXCLUDED.name_en,
        name_jp               = EXCLUDED.name_jp,
        rarity                = EXCLUDED.rarity,
        icon_id               = EXCLUDED.icon_id,
        available_in_en       = EXCLUDED.available_in_en,
        condition_groups_json = EXCLUDED.condition_groups_json,
        base_time_ms          = EXCLUDED.base_time_ms;
        -- NOTE: conditions_hash intentionally NOT updated here
END;
$$;

CREATE OR REPLACE PROCEDURE upsert_uma_skill(
    p_skill_id              INT,
    p_parent_skill_id       INT,
    p_name_en               VARCHAR(200),
    p_name_jp               VARCHAR(200),
    p_rarity                INT,
    p_icon_id               INT,
    p_available_in_en       BOOLEAN,
    p_condition_groups_json JSONB,
    p_conditions_hash       VARCHAR(64)
)
LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO uma_skills (
        skill_id, parent_skill_id, name_en, name_jp, rarity, icon_id,
        available_in_en, condition_groups_json, conditions_hash, last_updated
    )
    VALUES (
        p_skill_id, p_parent_skill_id, p_name_en, p_name_jp, p_rarity, p_icon_id,
        p_available_in_en, p_condition_groups_json, p_conditions_hash, NOW()
    )
    ON CONFLICT (skill_id) DO UPDATE
        SET name_en               = EXCLUDED.name_en,
            name_jp               = EXCLUDED.name_jp,
            rarity                = EXCLUDED.rarity,
            icon_id               = EXCLUDED.icon_id,
            available_in_en       = EXCLUDED.available_in_en,
            condition_groups_json = EXCLUDED.condition_groups_json,
            conditions_hash       = EXCLUDED.conditions_hash,
            last_updated          = NOW();
END;
$$;

CREATE OR REPLACE PROCEDURE upsert_uma_skill(
    p_skill_id              INT,
    p_parent_skill_id       INT,
    p_name_en               VARCHAR(200),
    p_name_jp               VARCHAR(200),
    p_rarity                INT,
    p_icon_id               INT,
    p_available_in_en       BOOLEAN,
    p_condition_groups_json JSONB,
    p_conditions_hash       VARCHAR(64),
    p_base_time_ms          INT
)
LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO uma_skills (
        skill_id, parent_skill_id, name_en, name_jp, rarity, icon_id,
        available_in_en, condition_groups_json, conditions_hash, base_time_ms
    )
    VALUES (
        p_skill_id, p_parent_skill_id, p_name_en, p_name_jp, p_rarity, p_icon_id,
        p_available_in_en, p_condition_groups_json, p_conditions_hash, p_base_time_ms
    )
    ON CONFLICT (skill_id) DO UPDATE SET
        parent_skill_id       = EXCLUDED.parent_skill_id,
        name_en               = EXCLUDED.name_en,
        name_jp               = EXCLUDED.name_jp,
        rarity                = EXCLUDED.rarity,
        icon_id               = EXCLUDED.icon_id,
        available_in_en       = EXCLUDED.available_in_en,
        condition_groups_json = EXCLUDED.condition_groups_json,
        conditions_hash       = EXCLUDED.conditions_hash,
        base_time_ms          = EXCLUDED.base_time_ms;
END;
$$;

CREATE OR REPLACE PROCEDURE upsert_uma_skill_characters(p_skill_id INT, p_char_ids INT[])
LANGUAGE plpgsql AS $$
BEGIN
    DELETE FROM uma_skill_characters WHERE skill_id = p_skill_id;

    INSERT INTO uma_skill_characters (skill_id, char_id)
    SELECT p_skill_id, unnest(p_char_ids)
    ON CONFLICT DO NOTHING;
END;
$$;

CREATE OR REPLACE PROCEDURE upsert_uma_skill_readable_group(
    p_skill_id              INT,
    p_group_index           INT,
    p_readable_precondition TEXT,
    p_readable_condition    TEXT,
    p_readable_effects      TEXT
)
LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO uma_skill_readable_groups
        (skill_id, group_index, readable_precondition, readable_condition, readable_effects)
    VALUES
        (p_skill_id, p_group_index, p_readable_precondition, p_readable_condition, p_readable_effects)
    ON CONFLICT (skill_id, group_index) DO UPDATE SET
        readable_precondition = EXCLUDED.readable_precondition,
        readable_condition    = EXCLUDED.readable_condition,
        readable_effects      = EXCLUDED.readable_effects;
END;
$$;


-- ============================================================
-- TRIGGERS
--
-- PostgreSQL triggers require a separate trigger function
-- (RETURNS TRIGGER) plus a CREATE TRIGGER statement.
-- ============================================================

-- Cleans up stored reposts when repost_check is turned off for a channel.
CREATE OR REPLACE FUNCTION fn_repost_cleanup() RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    -- Only act when repost_check transitions from TRUE to FALSE
    IF OLD.repost_check = TRUE AND NEW.repost_check = FALSE THEN
        DELETE FROM repost_repository WHERE channel_id = NEW.channel_id;
    END IF;
    RETURN NULL;
END;
$$;

CREATE TRIGGER repost_cleanup
AFTER UPDATE ON discord_channels
FOR EACH ROW EXECUTE FUNCTION fn_repost_cleanup();


-- Removes channels that are no longer useful after an update.
CREATE OR REPLACE FUNCTION fn_channel_cleanup_after_update() RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    CALL remove_useless_channels();
    RETURN NULL;
END;
$$;

CREATE TRIGGER channel_cleanup
AFTER UPDATE ON discord_channels
FOR EACH ROW EXECUTE FUNCTION fn_channel_cleanup_after_update();


-- Removes orphan twitter_rules (rules with no channel associations) after a rule-channel link is deleted.
CREATE OR REPLACE FUNCTION fn_rule_cleanup() RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    DELETE FROM twitter_rules
    WHERE tag NOT IN (SELECT rcr.tag FROM rule_channel_relation rcr);
    RETURN NULL;
END;
$$;

CREATE TRIGGER rule_cleanup
AFTER DELETE ON rule_channel_relation
FOR EACH ROW EXECUTE FUNCTION fn_rule_cleanup();


-- Removes channels made useless after a rule-channel link is deleted.
CREATE OR REPLACE FUNCTION fn_channel_cleanup_after_relation_delete() RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    CALL remove_useless_channels();
    RETURN NULL;
END;
$$;

CREATE TRIGGER channel_cleanup_relation
AFTER DELETE ON rule_channel_relation
FOR EACH ROW EXECUTE FUNCTION fn_channel_cleanup_after_relation_delete();
